namespace PayBridge.Domain.ValueObjects
{
    /// <summary>
    /// A base class that forces "Structural Equality." 
    /// Two instances are considered equal if all their internal values match, 
    /// regardless of their memory address.
    /// </summary>
    public abstract class ValueObject
    {
        /// <summary>
        /// Collects all properties that define the identity of the object.
        /// Derived classes must "yield return" each field that should be part of the equality check.
        /// </summary>
        /// <returns>An ordered collection of the object's identifying values.</returns>
        protected abstract IEnumerable<object?> GetEqualityComponents();

        /// <summary>
        /// Compares the current object with another. 
        /// It ensures they are of the same type and then compares their individual components in order.
        /// </summary>
        /// <param name="obj">The object to compare with the current instance.</param>
        /// <returns>True if all components match; otherwise, false.</returns>
        public override bool Equals(object? obj)
        {
            if (obj == null || obj.GetType() != GetType())
                return false;

            var other = (ValueObject)obj;

            return GetEqualityComponents()
                .SequenceEqual(other.GetEqualityComponents());
        }

        /// <summary>
        /// Creates a unique numeric "fingerprint" for the object.
        /// This is essential for performance when using the object in Collections like HashSets or Dictionaries.
        /// </summary>
        /// <returns>An integer hash code generated by combining the hashes of all equality components.</returns>
        public override int GetHashCode()
        {
            return GetEqualityComponents()
                .Select(x => x?.GetHashCode() ?? 0)
                .Aggregate((x, y) => x ^ y);
        }

        /// <summary>
        /// Replaces the default C# reference check (memory address) with our custom value-based comparison.
        /// Includes safety checks to handle null values on either side of the operator.
        /// </summary>
        public static bool operator ==(ValueObject? left, ValueObject? right)
        {
            if (left is null && right is null) return true;
            if (left is null || right is null) return false;
            return left.Equals(right);
        }

        /// <summary>
        /// The inverse of the equality operator, ensuring consistent logic for inequality checks.
        /// </summary>
        public static bool operator !=(ValueObject? left, ValueObject? right)
        {
            return !(left == right);
        }
    }
}